language: java

service:
  - docker
  
env:
  global:
    - IMAGE_NAME: alvarobacelar/productor-kafka-java

script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t $IMAGE_NAME:ssl .
  - docker push $IMAGE_NAME:ssl
