version: '2'
services:
   productor:
     image: alvarobacelar/productor-kafka-java:latest
     container_name: productor-kafka
     environment:
       - KAFKA_SERVER={{ hostvars[groups['kafka'][0]]['ansible_host'] }}:9092
       - KAFKA_TOPIC=test-topic
       - KAFKA_COUNT_MSG=100
       #- KAFKA_MSG=
