version: '2'
services:
   productor:
     image: alvarobacelar/productor-kafka-java:ssl
     container_name: productor-kafka
     environment:
       - KAFKA_SERVER={{ hostvars[groups['kafka'][0]]['ansible_host'] }}:9092
       - KAFKA_TOPIC=test-topic
       - KAFKA_COUNT_MSG=100
       - KAFKA_KEY=/root/client.truststore.jks
       - KAFKA_PASS={{ pass_key_kafka }}
       #- KAFKA_MSG=
     volumes:
       - /root/client.truststore.jks:/root/client.truststore.jks:ro
