version: '2'
services:
   productor:
     image: alvarobacelar/productor-kafka-java:latest
     container_name: productor-kafka
     environment:
       - KAFKA_SERVER=172.17.0.1:9092
       - KAFKA_TOPIC=meu-primeiro-topico
       - KAFKA_COUNT_MSG=10000
     extra_hosts:
       jarvis: 172.17.0.1 
       #- KAFKA_MSG=
